export const DUMMY_NEWS = [
  {
    id: "n1",
    slug: "project-manager-praha",
    title: "Project Manager",
    image: "project-manager.jpg",
    price: "70 - 90 000 Kč",
    location: "Praha",
    company: "XYZ Consulting s.r.o.",
    job: "HPP",
    date: "2021-08-15",
    content:
      "Hledáme zkušeného Project Managera pro řízení IT projektů. Pokud máte zkušenosti s vedením týmu a projektovým řízením, přihlaste se ještě dnes!",
  },
  {
    id: "n2",
    slug: "software-developer-brno",
    title: "Software Developer",
    image: "software-developer.jpg",
    price: "60 - 80 000 Kč",
    location: "Brno",
    company: "Tech Solutions a.s.",
    job: "HPP",
    date: "2021-08-20",
    content:
      "Staňte se součástí inovativního týmu jako Software Developer. Hledáme talentované programátory s vášní pro moderní technologie.",
  },
  {
    id: "n3",
    slug: "hr-specialist-ostrava",
    title: "HR Specialist",
    image: "hr-specialist.jpg",
    price: "50 - 70 000 Kč",
    location: "Ostrava",
    company: "HR Partners s.r.o.",
    job: "HPP",
    date: "2021-09-01",
    content:
      "Máte zkušenosti v oblasti lidských zdrojů? Připojte se k našemu týmu a pomozte nám budovat firemní kulturu a zaměstnanecké vztahy.",
  },
  {
    id: "n4",
    slug: "marketing-manager-plzen",
    title: "Marketing Manager",
    image: "marketing-manager.jpg",
    price: "65 - 85 000 Kč",
    location: "Plzeň",
    company: "Creative Minds a.s.",
    job: "HPP",
    date: "2021-09-10",
    content:
      "Hledáme kreativního Marketing Managera, který bude odpovědný za strategické řízení marketingových kampaní.",
  },
  {
    id: "n5",
    slug: "data-analyst-brno",
    title: "Data Analyst",
    image: "data-analyst.jpg",
    price: "55 - 75 000 Kč",
    location: "Brno",
    company: "Data Insights s.r.o.",
    job: "HPP",
    date: "2021-09-15",
    content:
      "Analyzujte data a pomáhejte firmám činit informovaná rozhodnutí. Hledáme Data Analytika se zkušeností s velkými daty.",
  },
  {
    id: "n6",
    slug: "graphic-designer-praha",
    title: "Graphic Designer",
    image: "graphic-designer.jpg",
    price: "50 - 70 000 Kč",
    location: "Praha",
    company: "Design Studio s.r.o.",
    job: "HPP",
    date: "2021-09-20",
    content:
      "Hledáme talentovaného Graphic Designera, který miluje vytváření vizuálních konceptů a pracuje s moderními nástroji.",
  },
  {
    id: "n7",
    slug: "junior-accountant-brno",
    title: "Junior Accountant",
    image: "junior-accountant.jpg",
    price: "40 - 60 000 Kč",
    location: "Brno",
    company: "Finance Experts a.s.",
    job: "HPP",
    date: "2021-09-25",
    content:
      "Začněte svou kariéru v účetnictví jako Junior Accountant. Nabízíme mentoring a podporu v růstu.",
  },
  {
    id: "n8",
    slug: "ux-ui-designer-praha",
    title: "UX/UI Designer",
    image: "ux-ui-designer.jpg",
    price: "70 - 90 000 Kč",
    location: "Praha",
    company: "Digital Experience s.r.o.",
    job: "HPP",
    date: "2021-09-30",
    content:
      "Hledáme UX/UI Designera, který vytvoří intuitivní uživatelské rozhraní a přinese jedinečný uživatelský zážitek.",
  },
  {
    id: "n9",
    slug: "customer-support-ostrava",
    title: "Customer Support Specialist",
    image: "customer-support.jpg",
    price: "30 - 50 000 Kč",
    location: "Ostrava",
    company: "HelpDesk Solutions s.r.o.",
    job: "HPP",
    date: "2021-10-01",
    content:
      "Máte rádi práci s lidmi? Připojte se k našemu týmu jako Customer Support Specialist a pomáhejte zákazníkům s jejich dotazy.",
  },
  {
    id: "n10",
    slug: "business-analyst-praha",
    title: "Business Analyst",
    image: "business-analyst.jpg",
    price: "80 - 100 000 Kč",
    location: "Praha",
    company: "Global Corp s.r.o.",
    job: "HPP",
    date: "2021-10-05",
    content:
      "Staňte se Business Analytikem v dynamickém prostředí a pomáhejte firmám realizovat jejich strategické cíle.",
  },
];
